### ISSUE TITLE
Better Error Handling for Empty Responses

### ISSUE THREAD

**Issue by fny** [plivo/plivo-ruby#37]
We got the following error in production today because the Plivo API returned an empty string as a response for some reason (first time we've ever seen this):

```
JSON::ParserError: A JSON text must at least contain two octets!
/app/vendor/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
-------------------------------
Backtrace:

/app/vendor/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
/app/vendor/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `new'
/app/vendor/bundle/ruby/2.2.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
/app/vendor/bundle/ruby/2.2.0/gems/plivo-0.3.16/lib/plivo.rb:82:in `request'
/app/vendor/bundle/ruby/2.2.0/gems/plivo-0.3.16/lib/plivo.rb:515:in `get_message'
```

``` ruby
JSON.parse('') # => JSON::ParserError
```

This should instead raise a Plivo specific error (e.g. `Plivo::NoResponseError`).

**Comment by tsudot** [comment]
@fny makes sense. However I'm not sure if I'll be able to work on this immediately. Could you send us a PR, would be happy to merge :)

**Comment by fny** [comment]
I would, but I'm a bit wary of making changes since there is no testing in place.

**Comment by plivo-sdks** [comment]
This issue has been marked as stale because it has not had recent activity and is now closed. Please open the issue if the solution is not found yet.
